name: CI

on:
  push:
    branches:
      - main

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "10.x"
      - run: npm install
      - run: npm run build
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_API_KEY: ${{secretes.FIREBASE_API_KEY}}
          FIREBASE_ATH_DOMAIN: ${{secretes.FIREBASE_ATH_DOMAIN}}
          FIREBASE_DATABASE_URL: ${{secretes.FIREBASE_DATABASE_URL}}
          FIREBASE_PROJECT_ID: ${{secretes.FIREBASE_PROJECT_ID}}
          FIREBASE_STORAGE_BUCKET: ${{secretes.FIREBASE_STORAGE_BUCKET}}
          FIREBASE_MESSAGING_SENDER_ID: ${{secretes.FIREBASE_MESSAGING_SENDER_ID}}
          FIREBASE_APP_ID: ${{secretes.FIREBASE_APP_ID}}
